In [4]:
marks=float(input("Enter your % "))
if (marks >= 60):
    print("First class")
elif (marks >= 50):
    print("Sencond class")
elif (marks >= 40):
    print("Pass class")
else:
    print("Better luck next time")

Enter your % 98
First class

In [5]:
str=int(input("enter a no:"))
end=int(input("enter a no:"))
if str<end:
    for i in range(str,end+1,1):
      print(i)
else:
    for i in range(str,end-1,-1):
      print(i)

enter a no:6
enter a no:1
6
5
4
3
2
1

In [1]:
sum=0
while True:
    i=input("Enter data:")
    if i=='':
        break
print("Ok bye")

Enter data:5
Enter data:5
Enter data:5
Enter data:58
Enter data:
Ok bye

In [2]:

sum=0.0
while True:
    i=input("Enter data:")
    if i=='':
        break
    sum+=float(i)
print("Sum is :",sum)

Enter data:1
Enter data:2
Enter data:6
Enter data:8
Enter data:10
Enter data:
Sum is : 27.0

In [4]:
x=0
y=1
count=0
total=0
while True:
    i=input("Enter data :")
    if i=='':
        break
    count+=1
    i=float(i)
    total+=i
    if (i%2==0):
        x+=i
    else:
        y*=i
print("Total elements:",count,"Sum :",x,"Product",y,"Average",total/count)

Enter data :2
Enter data :6
Enter data :8
Enter data :3
Enter data :5
Enter data :7
Enter data :
Total elements: 6 Sum : 16.0 Product 105.0 Average 5.166666666666667

In [9]:
count=0
for i in range (2000,3001,4):
    if (i%4==0 and i%100!=0) or (i%400==0):
        count+=1
        print(i)
print("Number of yrs",count)

2000
2004
2008
2012
2016
2020
2024
2028
2032
2036
2040
2044
2048
2052
2056
2060
2064
2068
2072
2076
2080
2084
2088
2092
2096
2104
2108
2112
2116
2120
2124
2128
2132
2136
2140
2144
2148
2152
2156
2160
2164
2168
2172
2176
2180
2184
2188
2192
2196
2204
2208
2212
2216
2220
2224
2228
2232
2236
2240
2244
2248
2252
2256
2260
2264
2268
2272
2276
2280
2284
2288
2292
2296
2304
2308
2312
2316
2320
2324
2328
2332
2336
2340
2344
2348
2352
2356
2360
2364
2368
2372
2376
2380
2384
2388
2392
2396
2400
2404
2408
2412
2416
2420
2424
2428
2432
2436
2440
2444
2448
2452
2456
2460
2464
2468
2472
2476
2480
2484
2488
2492
2496
2504
2508
2512
2516
2520
2524
2528
2532
2536
2540
2544
2548
2552
2556
2560
2564
2568
2572
2576
2580
2584
2588
2592
2596
2604
2608
2612
2616
2620
2624
2628
2632
2636
2640
2644
2648
2652
2656
2660
2664
2668
2672
2676
2680
2684
2688
2692
2696
2704
2708
2712
2716
2720
2724
2728
2732
2736
2740
2744
2748
2752
2756
2760
2764
2768
2772
2776
2780
2784
2788
2792
2796
2800
2804
2808
2812
2816
2820
2824
2828
2832
2836
2840
2844
2848
2852
2856
2860
2864
2868
2872
2876
2880
2884
2888
2892
2896
2904
2908
2912
2916
2920
2924
2928
2932
2936
2940
2944
2948
2952
2956
2960
2964
2968
2972
2976
2980
2984
2988
2992
2996
Number of yrs 243

In [ ]:
no=float(input('Enter a number :'))

In [10]:
Sum=0
i= int(input("enter the number"))
num=i
while(num!=0):
    unit=num%10
    Sum=Sum+unit**3
    num=num//10
if (i==Sum):
    print("Given number is amstrong number")
else:
    print("given number is not amstrong number")

enter the number153
Given number is amstrong number

0